---
deployment:
  tasks:
    - /bin/cp mvp/SVphone_v08_01/index.html /home/eznfmuyn/svphone.com/index.html
    - /bin/cp mvp/SVphone_v08_01/phone_interface.html /home/eznfmuyn/svphone.com/phone_interface.html
    - /bin/cp mvp/SVphone_v08_01/wallet.html /home/eznfmuyn/svphone.com/wallet.html
    - /bin/cp mvp/SVphone_v08_01/bundle.js /home/eznfmuyn/svphone.com/bundle.js
