---
deployment:
  tasks:
    - /bin/cp mvp/SVphone_v08_01/index.html $HOME/public_html/index.html
    - /bin/cp mvp/SVphone_v08_01/phone_interface.html $HOME/public_html/phone_interface.html
    - /bin/cp mvp/SVphone_v08_01/wallet.html $HOME/public_html/wallet.html
    - /bin/cp mvp/SVphone_v08_01/bundle.js $HOME/public_html/bundle.js
